config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/generate_csv.rb
module GenerateCsv
	extend ActiveSupport::Concern

	class_methods do
		def to_csv(collection)
			CSV.generate(col_sep: ";") do |csv|
				csv << attribute_names
				# csv << column_name
				collection.find_each do |record|
					csv << record.attributes.values
				end
			end
		end
	end

end

app/models/planning.rb
class Planning < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	include GenerateCsv
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def import
    file = params[:file]
    return redirect_to users_path, notice: "Ony CSV" unless file.content_type == "text/csv"

    CsvImportUsersService.new.call(file)
    
    redirect_to users_path, notice: "Imported"
  end

  # GET /users or /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.csv do
        send_data User.to_csv(@users), filename: "#{Date.today.to_s}.csv",content_type:"text/csv"
      end
    end
  end


  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email_address, :favorite_food, :mobile_phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImpExpFilesRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email_address, style: "display: block" %>
    <%= form.text_area :email_address %>
  </div>

  <div>
    <%= form.label :favorite_food, style: "display: block" %>
    <%= form.text_area :favorite_food %>
  </div>

  <div>
    <%= form.label :mobile_phone_number, style: "display: block" %>
    <%= form.text_area :mobile_phone_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email address:</strong>
    <%= user.email_address %>
  </p>

  <p>
    <strong>Favorite food:</strong>
    <%= user.favorite_food %>
  </p>

  <p>
    <strong>Mobile phone number:</strong>
    <%= user.mobile_phone_number %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<%#= link_to "Download", users_path(format: :csv), download: ["Users", Date.today].join(" ") %>
<%= link_to "Download", users_path(format: :csv) %>
<div id="users">

<div>
  <%= @users.count %>
</div>


<%= form_with url: import_users_url, method: :post do |form| %>
  <%= form.file_field :file, accept: ".csv" %>
  <%= form.button "Import" %>
<% end %>


<%= link_to "New user", new_user_path %>

  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>